runtime: nodejs12

env_variables:
  QUEUE_NAME: 'create-pdf-queue'
  QUEUE_LOCATION: 'asia-northeast1'
  FUNCTION_URL: 'https://asia-northeast1-pdf-test-77e7c.cloudfunctions.net/createPdfTaskHandler'

includes:
  - secret.yaml

# Handlers for serving the index page.
handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: index.html
    upload: index.html
